=== zorgzorg/XML-parsing/target/classes/salad.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">
    <xs:element name="salad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ingredient">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="vegetable" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name"/>
                                        <xs:element type="xs:byte" name="caloricvalue"/>
                                        <xs:element type="xs:short" name="weight"/>
                                        <xs:element type="xs:string" name="unit"/>
                                        <xs:element type="xs:string" name="preliminaryprocessing"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="dressing" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name"/>
                                        <xs:element type="xs:short" name="caloricvalue"/>
                                        <xs:element type="xs:byte" name="weight"/>
                                        <xs:element type="xs:string" name="unit"/>
                                        <xs:element type="xs:string" name="lenten"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="seasoning" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="name"/>
                                        <xs:element type="xs:short" name="caloricvalue"/>
                                        <xs:element type="xs:byte" name="weight"/>
                                        <xs:element type="xs:string" name="unit"/>
                                        <xs:element type="xs:byte" name="hotlevel"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== zorgzorg/XML-parsing/src/main/resources/salad.xml
<?xml version="1.0"?>
<salad xmlns="https://www.w3schools.com"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://www.w3schools.com salad.xsd"
       name="Винегрет с соленым огурцом">
    <ingredient>
        <vegetable>
            <name>Картофель вареный</name>
            <caloricvalue>82</caloricvalue>
            <weight>210</weight>
            <unit>г</unit>
            <preliminaryprocessing>true</preliminaryprocessing>
        </vegetable>
        <vegetable>
            <name>Свекла вареная</name>
            <caloricvalue>49</caloricvalue>
            <weight>150</weight>
            <unit>г</unit>
            <preliminaryprocessing>true</preliminaryprocessing>
        </vegetable>
        <vegetable>
            <name>Соленый огурец</name>
            <caloricvalue>11</caloricvalue>
            <weight>210</weight>
            <unit>г</unit>
            <preliminaryprocessing>false</preliminaryprocessing>
        </vegetable>
        <vegetable>
            <name>Морковь вареная</name>
            <caloricvalue>25</caloricvalue>
            <weight>100</weight>
            <unit>г</unit>
            <preliminaryprocessing>true</preliminaryprocessing>
        </vegetable>
        <vegetable>
            <name>Лук репчатый</name>
            <caloricvalue>47</caloricvalue>
            <weight>150</weight>
            <unit>г</unit>
            <preliminaryprocessing>false</preliminaryprocessing>
        </vegetable>
        <dressing>
            <name>Масло оливковое</name>
            <caloricvalue>898</caloricvalue>
            <weight>50</weight>
            <unit>мл</unit>
            <lenten>true</lenten>
        </dressing>
        <dressing>
            <name>Уксус бальзамический</name>
            <caloricvalue>88</caloricvalue>
            <weight>50</weight>
            <unit>мл</unit>
            <lenten>true</lenten>
        </dressing>
        <seasoning>
            <name>Сахар</name>
            <caloricvalue>398</caloricvalue>
            <weight>4</weight>
            <unit>г</unit>
            <hotlevel>0</hotlevel>
        </seasoning>
        <seasoning>
            <name>Соль</name>
            <caloricvalue>0</caloricvalue>г
            <weight>2</weight>
            <unit>г</unit>
            <hotlevel>0</hotlevel>
        </seasoning>
        <seasoning>
            <name>Перец черный молотый</name>
            <caloricvalue>251</caloricvalue>г
            <weight>1</weight>
            <unit>г</unit>
            <hotlevel>3</hotlevel>
        </seasoning>
    </ingredient>
</salad>
